### ISSUE TITLE
Feature name aliases

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/nucmorph-colorizer#57]
## Use Case

Scientists are requesting that the features be renamed (currently `NUC_shape_volume_lcc` and `NUC_position_depth`) to more human-readable names (`Depth` or `Volume`?)

## Acceptance Criteria

- Change feature names in the default dataset
- Future datasets generated by `generate_data.py` should also have matching feature aliases.

## Details
This can be edited pretty easily in the existing datasets but this should also be done within the data generation script. (Currently the features are hardcoded: just add a string dictionary, perhaps?)

**Comment by toloudis** [comment]
Note that the current names we use are the names of columns in the raw data for nucmorph so in order to add a feature to a dataset for this viewer, we need enough info to extract the data and also provide the "display name" for the feature.

In general, some future version of the data prep script will rely on a computational scientist to provide the input data for every feature, including display name and list of values.

**Comment by toloudis** [comment]
Bonus: there may be a more extensible "feature metadata" section in the data
