### ISSUE TITLE
use track id as a colorizable feature (discrete valued features)

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/nucmorph-colorizer#73]
## Use Case

I want to color by track id. 

## Acceptance Criteria

Probably need to add support for discrete-valued features, just mapping id to color value and maintaining that mapping across time.  Design/implementation needs more spec.

## Details

User: could we have track id as one extra feature?
Engr: Yes but the colorizer is doing a linear color map lookup based on the feature’s relative value between min and max.   I think we might want to treat track ID in a different way, like as a discrete-valued feature.  That will mean some new code
User: That would be a great add.

**Comment by ShrimpCryptid** [comment]
https://spectrum.adobe.com/page/color-for-data-visualization/

**Comment by toloudis** [comment]
Other use cases: classifiers, such as "mitotic stage" etc.

**Comment by ShrimpCryptid** [comment]
Possibly defer, needs UX clarification

**Comment by toloudis** [comment]
Need to talk to users... check in with @lynwilhelm .
Questions:
- how would colors be assigned? 
- what's the largest number of discrete values?  (track ids can go very high, as opposed to categorical features like mitotic stage)
- assuming that order doesn't matter?
- do we need a legend?

**Comment by ShrimpCryptid** [comment]
- How does this interact with filters? (checkboxes for enabling/disabling each category specifically?)
- Can any feature be made categorical, or does it need to be defined at the dataset-level?

**Comment by ShrimpCryptid** [comment]
![image](https://github.com/allen-cell-animated/nucmorph-colorizer/assets/30200665/5a37b3e1-471d-48d5-b985-fdfbf130ab47)

**Comment by lynwilhelm** [comment]
### Description
-Discovery work needed around how to handle discrete values and associated colors in the visualization
-Users need a way to colorize the data when it's not regular continuous values
- Will involve scheduling a session for input with 2-4 scientists

***
_Below to be filled out by UX during kickoff Q&A to the best of current understanding_

### Size
_Effort level (xs, sm, m, lg, xl)_
Gonna guess XS for UX

### Scope
_What will we do? What will we NOT do?_
This is still TBD and will be agreed on after talking to users

### User needs statement(s)
As a _[type of user]_, I need/want to _[action(s)]_, so that I can _[goal]_.

### Additional notes
_Knowns/unknowns, stakeholders, time/dependency considerations, deliverables_
This will be a short turn around of intake of info, then choosing most optimal solution with development. I will provide any designs that are needed for guidance.

**Comment by toloudis** [comment]
showing colors in legend will be a separate ticket

**Comment by lynwilhelm** [comment]
@ShrimpCryptid Here is the design link: https://www.figma.com/file/DcFEsrszbUOK0qU1E9wrH0/2023-Aug-NucMorph-Viz-App?type=design&node-id=667%3A3470&mode=design&t=3SHhzQgmYFjyMdGQ-1

**Comment by ShrimpCryptid** [comment]
Implementation issue ticket has moved to #148
